### ISSUE TITLE
OSX10.12.6下命令行安装出现错误unrecognized import path "bingo/bingo"

### ISSUE THREAD

**Issue by cjlcooper** [silsuer/bingo#1]
错误信息log:
package bingo/bingo: unrecognized import path "bingo/bingo" (import path does not begin with hostname)

**Comment by silsuer** [comment]
@cjlcooper 抱歉哈，昨天改动不小，忘了更改示例文件了，原因是我本地的路径和你的路径不同，原来的import的是“bingo/bingo”，改成“github.com/silsuer/bingo/bingo”就好了，我已经commit了新的，重新get下应该就可以了

**Comment by cjlcooper** [comment]
@silsuer Thx
