### ISSUE TITLE
这是什么鬼？

### ISSUE THREAD

**Issue by linux-mac** [silsuer/bingo#4]
<img width="823" alt="wx20181207-102512 2x" src="https://user-images.githubusercontent.com/6309187/49623914-8737d400-fa0a-11e8-8e13-93262374059c.png">

**Comment by silsuer** [comment]
@linux-mac 老哥，能把你的操作过程给我看看么，没有见过怎么会出现这种方式.. 这个`terminal prompts disabled` 错误倒是可以用 `GIT_TERMINAL_PROMPT=1` 来解决，但是我不知道为什么会加载test包，所以把您的操作过程让我看看吧，感谢反馈

**Comment by silsuer** [comment]
@linux-mac 您好，已经找到了bug了，您可以删掉bingo，重新 `go get` 然后再次创建试试哈~
