### ISSUE TITLE
依赖里面需要下载test，但是连接是404

### ISSUE THREAD

**Issue by jeffrey9898** [silsuer/bingo#5]
https://github.com/silsuer/test

这么大个问题作者没有发现么？

另外就是这个go get之后，没有bingo命令，需要先到目录下go install，这点也没提到。对于新手来说很尴尬

**Comment by silsuer** [comment]
！！！
@jeffrey9898  
感谢！
是创建项目时候有一个位置忘记替换了！我这里因为有这个项目存在，所以忽略掉了，没有测出来
刚刚修复了，现在您可以删掉`bingo`重新 `go get`然后 `create`再试试~
再次感谢试用~

**Comment by silsuer** [comment]
@jeffrey9898 还有一件事哈，`go get -v github.com/silsuer/bingo ` 会自动进行 `go install` 呀，我刚刚测试过，是会执行install的，我把这个放到文档里哈，感谢指出！第一次写开源程序，不知道该写点啥~
